image: docker:latest

services:
  - name: docker:dind
    alias: docker
    command: ["--tls=false"]


stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY: 724772066880.dkr.ecr.eu-west-1.amazonaws.com
  APP_NAME: "dev-clync-frontend"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_NETWORK_OPTIONS: --dns 8.8.8.8


.template_docker_login:
  image: docker:latest
  services:
    - docker:dind  

.template_aws:
  image: amazon/aws-cli 


build-image-dev:
  stage: build
  variables:
    DOCKER_REGISTRY: 724772066880.dkr.ecr.eu-west-1.amazonaws.com
    APP_NAME: dev-clync-frontend
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - name: docker:dind 
      command: ["--tls=false"] 
  extends: .template_docker_login
  before_script:
    - amazon-linux-extras install docker  # Install Docker in amazon/aws-cli
    - docker --version
    - aws --version
  script:
    - unset DOCKER_HOST
    - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker build  -t clync-frontend/${CI_COMMIT_REF_NAME}:latest .
    - docker tag clync-frontend/${CI_COMMIT_REF_NAME}:latest  $DOCKER_REGISTRY/$APP_NAME:${CI_PIPELINE_IID}
    - docker push   $DOCKER_REGISTRY/$APP_NAME:${CI_PIPELINE_IID}
    - docker logout

  #after_script:
   # - docker system prune -af  --filter "until=$((24))h" --filter "label=scope=agent-${CI_COMMIT_REF_NAME}-${APP_NAME}"  
  environment: development  
  #when: manual
  rules:
    - if:  '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "dev" '
      exists:
        - Dockerfile


deploy-dev:
  stage: deploy
  image:
    name: ubuntu:latest
    entrypoint: [""]
  extends: .template_docker_login  
  before_script:
   # Install SSH and configure SSH Agent
    - apt-get update && apt-get install -y openssh-client
    - echo "test ubuntu pipline "
  script:
    #- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - # ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST
    - chmod 400 "gitlab-server.pem"
    - ssh -o "StrictHostKeyChecking no" -i "gitlab-server.pem" ubuntu@ec2-34-242-133-82.eu-west-1.compute.amazonaws.com "aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $DOCKER_REGISTRY"
    # Stop the old container
    - ssh  -o "StrictHostKeyChecking no" -i "gitlab-server.pem" ubuntu@ec2-34-242-133-82.eu-west-1.compute.amazonaws.com "docker stop ${APP_NAME}_container || true && docker rm ${APP_NAME}_container || true"
    # Pull the new image
    - ssh -o "StrictHostKeyChecking no" -i "gitlab-server.pem" ubuntu@ec2-34-242-133-82.eu-west-1.compute.amazonaws.com "docker pull $DOCKER_REGISTRY/$APP_NAME:${CI_PIPELINE_IID}"
    # Run the new container
    - ssh -o "StrictHostKeyChecking no" -i "gitlab-server.pem" ubuntu@ec2-34-242-133-82.eu-west-1.compute.amazonaws.com "docker run -d --name ${APP_NAME}_container -p 9010:3000 $DOCKER_REGISTRY/$APP_NAME:${CI_PIPELINE_IID}"
    # Cleanup old containers/images
    - ssh -o "StrictHostKeyChecking no" -i "gitlab-server.pem" ubuntu@ec2-34-242-133-82.eu-west-1.compute.amazonaws.com "docker image prune -a -f"

  environment: development
  rules:
    - if:  '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "dev" '
      exists:
        - Dockerfile