import type { Metadata } from "next";
import { Inter, Montserrat, Figtree, Poppins, Roboto } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800" , "900"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["500", "600", "800"],
});

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400"],
});

const mokoko = Roboto({
  variable: "--font-mokoko",
  subsets: ["latin"],
  weight: ["700"], // Matches your CSS font-weight: 700
});

export const metadata: Metadata = {
  title: "Clync",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${montserrat.variable} ${figtree.variable} ${poppins.variable} ${mokoko.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}